spring:
  application:
    name: spring-ai
  ai:
#    vectorstore:
#      redis:
#        initialize-schema: true # 是否初始化向量库索引
#        index: spring_ai_index # redis index name
#        prefix: "doc:" # prefix for the vector store
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
#  data:
#    redis:
#      host: 192.168.101.128
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.128:3306/ai_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: chen1234
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.chen.springaidemo: debug

# 生产环境关闭
springdoc:
  api-docs:
    enabled: true # 开启openAPI接口
    path: /use-server/v3/api-docs
  swagger-ui:
    enabled: true
    path: /use-server/swagger-ui
server:
  port: 10010
